openapi: 3.1.0
info:
  title: allOf Demo
  version: '2022-05-03'
  description: |
    Example for a blog post about [extending schemas with `allOf`](https://redocly.com/blog/all-of-schemas/).
    The try it and code samples interact with [mock servers](https://redocly.com/docs/api-registry/guides/mock-server-quickstart/). 
servers:
  - url: https://631a7ab8-509f-48a7-8594-5ca628a803e4.remockly.com
    description: Mock server
paths:
  /addresses:
    post:
      summary: Create address
      operationId: createAddress
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddressRequired"
      responses:
        '201':
          description: Address created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
  /addresses/{id}:
    patch:
      parameters:
        - name: id
          in: path
          required: true
          description: ID of address
          schema:
            type: string
      summary: Update address
      operationId: updateAddress
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/Address"
            examples:
              corporate:
                summary: Redocly HQ
                value:
                  line1: Redocly HQ
                  line2: Suite 72
                  city: Austin
              ukraine:
                summary: Redocly Lviv
                value:
                  line1: 123 City Center
                  line2: 3rd Floor
                  city: Lviv
                  
      responses:
        '200':
          description: Address updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
              examples:
                corporate:
                  summary: Redocly HQ
                  value:
                    id: 123-hq
                    line1: Redocly HQ
                    line2: Suite 72
                    city: Austin
                ukraine:
                  summary: Redocly Lviv
                  value:
                    id: 456-lviv
                    line1: 123 City Center
                    line2: 3rd Floor
                    city: Lviv
                
components:
  schemas:
    Address:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        line1:
          type: string
          example: 123 Main Street
        line2:
          type: string
          example: Suite 301
        city:
          type: string
          example: Austin
    AddressRequired:
      allOf:
        - $ref: "#/components/schemas/Address"
        - required:
          - line1
          - city
